# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shiham Samsudeen
email: shihams247@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Shiham Samsudeen from Sri Lanka. A tech enthusiast creating all things web with a tap to the latest of tech trends!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shihamsam.github.io" # the base hostname & protocol for your site
twitter_username: shihams
github_username:  shihamsam

# Build settings
markdown: kramdown
